dist: xenial
language: rust
rust:
  - stable
cache: 
 directories:
  - $HOME/.cargo
  - .build

before_install:
  - sudo apt-get install qrencode
  - sudo apt-get install ocaml
  - sudo apt-get install inkscape
  - sudo apt-get install imagemagick
  - sudo apt-get install cmake
  - sudo apt-get install build-essential
  - sudo apt-get install moreutils
  - sudo apt-get install texlive-base texlive-lang-german texlive-lang-english texlive-luatex latexmk texlive-latex-recommended texlive-font-utils texlive-fonts-recommended cm-super t1utils texlive-latex-extra texlive-generic-recommended fonts-lmodern texlive-xetex
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install mdbook)
  - cargo install-update -a

# Command for installing dependencies
install:
  - curl https://raw.githubusercontent.com/ImageMagick/ImageMagick/b92c2698747fc132ee35ff00e3aab46f4715ca6e/config/policy.xml > policy.xml
  - sudo mv policy.xml /etc/ImageMagick-6/policy.xml
  - (wget https://ftp.gnu.org/gnu/make/make-4.2.1.tar.gz && tar -xf make-4.2.1.tar.gz && cd make-4.2.1 && ./configure && make && sudo make install)
  - wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && sudo mv jq-linux64 /usr/local/bin/jq && chmod +x /usr/local/bin/jq
  - make --version 
  - make init
  - make doc 

# Commands for running the tests
script:
  - make exports/articles/latest/latex/print/Mathe_f端r_Nicht-Freaks@COLON@_Uneigentliches_Supremum_und_Infimum/839516.tex -j1
  - make exports/articles/latest/pdf/verbose/Mathe_f端r_Nicht-Freaks@COLON@_Uneigentliches_Supremum_und_Infimum/839516.pdf -j1
  - make exports/articles/latest/html/all/Mathe_f端r_Nicht-Freaks@COLON@_Epsilon-Delta-Kriterium_der_Stetigkeit/839108.html -j1
  - make exports/articles/latest/stats/all/Mathe_f端r_Nicht-Freaks@COLON@_Epsilon-Delta-Kriterium_der_Stetigkeit/latest.stats.html -j10
  - make exports/Benutzer@COLON@Valentin_Roland@SLASH@Analysis_1/latest/html/all/latest.book.html -j
  - make exports/Benutzer@COLON@Valentin_Roland@SLASH@Analysis_1/latest/latex/print/latest.book.tex -j
  - make exports/Benutzer@COLON@Valentin_Roland@SLASH@Analysis_1/latest/pdf/minimal/latest.book.pdf -j

# deploy documentation to pages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: doc/book/
  keep-history: false
  on:
    branch: master
