language: python

python: '3.5'

cache:
  cargo: true
  pip: true
  directories:
    - /tmp/texlive
    - $HOME/.texlive

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
  - export PATH=~/.cargo/bin:$PATH
  - sudo apt-get -qq update
  - sudo apt-get install qrencode
  - sudo apt-get install ocaml
  - sudo apt-get install inkscape
  - sudo apt-get install imagemagick
  - sudo apt-get install latexmk
  - sudo apt-get install texlive-full
  - sudo apt-get install texlive-lang-german
  - sudo apt-get install cmake
  - sudo apt-get install build-essential
  - (git clone https://github.com/commonmark/cmark.git && cd cmark-gfm && mkdir build && cd build && cmake .. && sudo make install)

# Command for installing dependencies
install: make init

# Commands for running the tests
script:
  - make article_exports/pdf/print/Mathe_für_Nicht-Freaks@COLON@_Uneigentliches_Supremum_und_Infimum/839516.tex
  - make article_exports/html/all/Mathe_für_Nicht-Freaks@COLON@_Epsilon-Delta-Kriterium_der_Stetigkeit/839108.html
  - make article_exports/stats/all/Mathe_für_Nicht-Freaks@COLON@_Epsilon-Delta-Kriterium_der_Stetigkeit/839108.stats.html
  - make book_exports/Benutzer@COLON@Valentin_Roland@SLASH@Analysis_1/861124/html/all/861124.html
  - make book_exports/Benutzer@COLON@Valentin_Roland@SLASH@Analysis_1/861124/pdf/print/861124.pdf
