language: rust
rust:
  - stable
cache: 
 directories:
  - $HOME/.cargo
  - .build

before_install:
  - sudo apt-get install qrencode
  - sudo apt-get install ocaml
  - sudo apt-get install inkscape
  - sudo apt-get install imagemagick
  - sudo apt-get install cmake
  - sudo apt-get install build-essential
  - sudo apt-get install python3
  - sudo apt-get install python-virtualenv
  - sudo apt-get install moreutils
  - sudo apt-get install texlive-latex-base

# Command for installing dependencies
install: 
  - (git clone https://github.com/commonmark/cmark.git && cd cmark && mkdir build && cd build && cmake .. && sudo make install) 
  - (wget https://ftp.gnu.org/gnu/make/make-4.2.1.tar.gz && tar -xf make-4.2.1.tar.gz && cd make-4.2.1 && ./configure && make && sudo make install)
  - make --version 
  - virtualenv -p python3 venv
  - source venv/bin/activate
  - make init

# Commands for running the tests
script:
  - make exports/articles/latest/latex/print/Mathe_für_Nicht-Freaks@COLON@_Uneigentliches_Supremum_und_Infimum/839516.tex -j1
  - make exports/articles/latest/html/all/Mathe_für_Nicht-Freaks@COLON@_Epsilon-Delta-Kriterium_der_Stetigkeit/839108.html -j1
  - make exports/articles/latest/stats/all/Mathe_für_Nicht-Freaks@COLON@_Epsilon-Delta-Kriterium_der_Stetigkeit/latest.stats.html -j10
  - make exports/Benutzer@COLON@Valentin_Roland@SLASH@Analysis_1/latest/html/all/latest.book.html -j
  - make exports/Benutzer@COLON@Valentin_Roland@SLASH@Analysis_1/latest/latex/print/latest.book.tex -j
