---
targets:
  latex.all:
    Latex:
      opts:
        page_width: 210
        page_height: 297
  latex.print:
    Latex: {}
  deps:
    Dependencies: {}
  sections:
    Sections: {}
  pdf.all:
    PDF: {}
  pdf.print:
    PDF:
      page_trim: 10
