---
targets:
  latex.verbose:
    Latex:
      centered_image_captions: true
      with_todo: true
      environment_numbers: true
  latex.all:
    Latex: {}
  latex.print:
    Latex:
      with_noprint: false
  latex.minimal:
    Latex: {}

  pdf.verbose:
    PDF: 
      page_width: 210
      page_height: 297
  pdf.all:
    PDF: 
      page_width: 210
      page_height: 297
  pdf.minimal:
     PDF: 
      page_width: 210
      page_height: 297   
  pdf.print:
    PDF:
      page_trim: 10

  html.verbose:
    HTML:
      with_todo: true
  html.all:
    HTML: {}
  html.print:
    HTML:
      hoist_thumbnails: true
  html.minimal:
    HTML: {}

  # generates dependencies for articles
  section-deps:
    SectionDeps: {}
  media-deps:
    MediaDeps: {}

  # extracts <section>s from articles
  sections:
    Sections: {}

  # extracts anchors (link targets) from articles
  anchors:
    Anchors: {}
       

  # stats targets for lints and more
  stats.verbose:
    Stats: {}
  stats.all:
    Stats: {}
  stats.print:
    Stats: {}
  stats.minimal:
    Stats: {}
