---
targets:
  latex.all:
    Latex:
      centered_image_captions: true
      with_todo: true
      environment_numbers: true
  latex.print:
    Latex:
      centered_image_captions: false
  latex.minimal:
    Latex:
      centered_image_captions: false

  pdf.minimal:
    PDF: {}
  pdf.all:
    PDF: 
      page_width: 210
      page_height: 297
  pdf.print:
    PDF:
      page_trim: 10

  html.all:
    HTML:
      with_todo: true
  html.print:
    HTML: {}
  html.minimal:
    HTML: {}

  # generates dependencies for articles
  section-deps:
    SectionDeps: {}
  media-deps:
    MediaDeps: {}

  # extracts <section>s from articles
  sections:
    Sections: {}

  # stats targets for lints and more
  stats.all:
    Stats: {}
  stats.print:
    Stats: {}
  stats.minimal:
    Stats: {}
