---
targets:
  # export everything, including information like todo and verbose captions
  verbose:
    - Latex:
        centered_image_captions: true
        with_todo: true
        environment_numbers: true
    - PDF: 
        page_width: 148
        page_height: 210
    - HTML:
        with_todo: true
    - Stats: {}

  # include everything
  all:
    - Latex: {}
    - PDF: 
        page_width: 148
        page_height: 210 
    - HTML: {}
    - Stats: {}

  # suitable for print, excluding some exercises or illustratory examples
  print:
    - Latex:
        with_noprint: false
    - PDF:
        page_width: 148
        page_height: 210
    - HTML:
        hoist_thumbnails: true
    - Stats: {}
 
  # like print, but in wideprint format
  print_wideprint:
    - Latex:
        with_noprint: false
    - PDF:
        page_trim: 10
        page_width: 155
        page_height: 235
 
  # a minimal book 
  minimal:
    - Latex: {}
    - PDF: 
        page_width: 148
        page_height: 210
    - HTML: {}
    - Stats: {}

  # targets which do not deviate from the default
  default:
    - SectionDeps: {}
    - MediaDeps: {}
    - Sections: {}
    - Anchors: {}
    - Normalize: {}
    - Compose: {}
