---
targets:
  latex.all:
    Latex:
      centered_image_captions: false
  latex.print:
    Latex:
      centered_image_captions: false
  latex.minimal:
    Latex:
      centered_image_captions: false

  section-deps:
    SectionDeps: {}
  media-deps:
    MediaDeps: {}

  sections:
    Sections: {}

  pdf.minimal:
    PDF: {}
  pdf.all:
    PDF: 
      page_width: 210
      page_height: 297
  pdf.print:
    PDF:
      page_trim: 10
